# -*- coding: utf-8 -*-
"""Loops y condicionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdVxJdFni3wNL0xcKXAlqc3twzvTIlKY

#Condicionales normales

Los condicionales son estructuras que reciben un valor de verdad o algo que se pueda comprender como tal y ejecuta el bloque de código que le sigue.
"""

B=2
if B<3:
  print("B es verdad")

A=[0]

if A:
  print("A es verdad")

"""Los condicionales nos permiten escribir código diferenciado, si por ejemplo quisieramos encontrar el valor absoluto de un número lo podríamos hacer de la siguiente manera:"""

numero=-2
if numero>=0:
  valor=numero
elif numero<0:
  valor=-numero
print(valor)

"""El código anterior es equivalente al siguiente si esperamos que la entrada "numero" siempre sea un numero entero:"""

if numero>=0:
  valor=numero
else:
  valor=-numero
print(valor)

"""Hagamos un ejemplo con algo de lógica"""

numero1=100
numero2=70
numero3=50

if numero1<1000 and numero2>10:
  print(" el numero 3 es: ", numero3)

"""Otro ejemplo con listas"""

lista=[]

if not lista:
  lista.append(1)
else:
  print("la lista tiene algo")

lista

not False

"""#loops

Las iteraciones o loops son estructuras que permiten repetir un proceso, vamos a ver las principales formas en las que se presentan

##while
"""

i=0
print("los dígitos en base 10 son: ")
while i<10:
  print(i)
  i+=1

i

"""Son muy utiles para solucionar problemas que requieren diferenciación"""

lista=["clara",0.37,"emma",0.48,"carlos",0.58,"angel",0.75,"fin1"]
nombres=[]
calificaciones=[]
i=0
valor=len(lista)
while lista[i]!="":
  a=lista[i]
  if type(a)==str:
    nombres.append(a)
  elif type(a)==float :
    calificaciones.append(a)
  i+=1
  if i==valor-1:
    break

print(nombres)
print(calificaciones)

i

"""Tambien sirve para permanecer en un proceso repetitivo en donde siempre se cumple la condición. Esto mal utilizado puede bloquear el computador."""

while True:
  print("hola")

"""##for

Los for loops son igualmente flexibles y mas comunes que los while en estructuras limitades de información, especialmente si incluimos el comando break
"""

datos=[0,1,2,3,4,5,6,7,8]
for i in datos:
  print(i)

for i in range(0,7):
  for j in range(9,11):
    if i==5:
      break
    print(i)

for i in range(0,7,2):
  print(i)

help(range)

"""Las grandes ventajas que tendremos de los loops van a ser al aprovechar otra forma de iteración, utilizando funciones como map. Vamos a hacer un ejercicio relativamente sencillo crearemos las tablas de multiplicar en un diccionario."""

tablas_de_multiplicar={}
for i in range(1,135):
  tabla=[]
  for j in range(1,11):
    tabla.append(i*j)
  tablas_de_multiplicar["tabla del "+str(i)]=tabla

tablas_de_multiplicar

"""##Try

Los try son estructuras que permiten ejecutar codigo aún si se presenta un error lo podemos utilizar cuando tenemos información de muy mala calidad o si queremos ser insensibles a algún error en específico. Pero debemos tratar de evitarlos a toda costa.
"""

try:
  a=int("hola")
except:
  print("esto imprime si hay un error")
print("esto tiene que imprimir")

a

datos_malos=[6,6,155,28,"ay",25,[3,25],325,26,{"aqui hay":"un error"}]

numeros_desde_datos_malos=[]
for i in datos_malos:
  try:
    numeros_desde_datos_malos.append(int(i))
  except Exception as e:
    print("hubo un error de: ",e)

numeros_desde_datos_malos

datos_malos2=[6,6,155,28,"ay",25,[3,25],325,26,{"aqui hay":"un error"},""]

"""Podemos tener problemas graves al utilizar esto"""

while True:
  try:
    print("hola")
  except KeyboardInterrupt:
    ...

try:
  print(x)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong")

print("holita")

"""#Ejercicio

Haremos un ejercicio para ver lo útil que pueden ser estas estructuras, e introduciremos algunos paquetes para número aleatorios y visualizaciones sencillas
"""

import random
import plotly.express as px

medias=[]
largo_variables=10000
largo_datos=2
for i in range(0,largo_variables):
  valores=[]
  media=0
  for j in range (0,largo_datos):
    media+= random.uniform(1, 10)
  medias.append(media/largo_datos)

px.histogram(medias)

"""#Taller

Realizar tres simulaciones para la media y desviación estandar de los datos utilizando random.uniform, random.triangular y random.gauss, todas estas devuelven valores según diferentes distribuciones. Al finalizar comente dos resultados que le parecieron extraños. Si todo resultó como esperaba comente qué aspectos teóricos concuerdan con los resultados de las simulaciones.
"""

